version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}usingdockerapi
    build:
      context: .
      dockerfile: ./UsingDockerApi/Dockerfile

  client:
    image: client
    build:
      context: ./using-docker-client
      dockerfile: Dockerfile

  proxy:
    image: nginx:mainline
